server:
  port: 8080

spring:
  data:
   redis:
     cluster:
       nodes:
         - 70.25.26.161:6379
         - 70.25.26.161:6380
         - 70.25.26.162:6379
         - 70.25.26.162:6380
         - 70.25.26.163:6379
         - 70.25.26.163:6380
     password: ehalsh!@#123


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
    region:
      static: ap-northeast-1
      auto: false
    stack:
      auto: false

    S3:
      bucket: s3-dominos-public-test

    sns:
      topic:
        arn: arn:aws:sns:ap-northeast-1:985883263647:MyTopic2

    sqs:
      queue:
        name: MyQueue2
        url: https://sqs.ap-northeast-1.amazonaws.com/985883263647/MyQueue2


