server:
  port: 8080

spring:
  data:
   redis:
     cluster:
       nodes:
         - x.x.x.x:6379
         - x.x.x.x:6380
         - x.x.x.x:6379
     password: xxxxxxxx


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
    region:
      static: ap-northeast-1
      auto: false
    stack:
      auto: false

    S3:
      bucket: s3-test-public-test

    sns:
      topic:
        arn: arn:aws:sns:ap-northeast-1:11111111:MyTopic2

    sqs:
      queue:
        name: MyQueue2
        url: https://sqs.ap-northeast-1.amazonaws.com/11111111/MyQueue2


